resolver: lts-21.21

packages:
- .

extra-deps:
  - clash-prelude-1.8.1
  - clash-lib-1.8.1
  - clash-ghc-1.8.1

ghc-options:
  "$everything": -O2 -threaded

flags:
  clash-prelude:
    super-errors: false

snapshot-file: stack-lts.yaml

nix:
  enable: false
